---
title: "population_count"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error=FALSE,message= FALSE,warning = FALSE)
```

## データ参考

https://www.e-stat.go.jp/dbview?sid=0003412313  
クロス集計表形式  
日本の総人口2019年10月  
総人口126,167　男性人口61,411　女性人口64,756  
このデータからデータ操作およびグラフ作成を行う

```{r data}
population <- data.frame(read.csv("FEH_00200524_210213170509.csv",
                                  skip =12),encoding="CP932")
#skipで12行目から読み込む
summary(population)
names(population)
```

## データ操作-1
列から不要なものを除く。  
下の名前があるものを除く
```{r}
population2 <- population[, !(colnames(population)
                   %in% c("時間軸.年月日現在..コード",
                          "全国.コード",
                          "全国",
                          "時間軸.年月日現在.",
                          "X.男女別.性比",
                          "encoding"))]
head(population2)
```


## 1行目が総数になっていたのでそれを除く。
```{r}
population2 <- population2[!(rownames(population2) ==1), ]
#複数でも対応できる。1,2行目複数の場合、下記のように1,2などにする
#population2 <- population2[!(rownames(population2) %in% c(1,2)), ]
head(population2)
```



## 年齢コードから年齢情報を持ってくるようにする。
年齢コードから1001引けば年齢になるデータになっているのを見出したので実施

```{r}
population2$"年齢各歳.コード" <- population2$"年齢各歳.コード"-1001
head(population2)
```


## 列名変更
```{r}
colnames(population2)[1] <- "年齢"
colnames(population2)[3] <- "総人口"
colnames(population2)[4] <- "総人口.男"
colnames(population2)[5] <- "総人口.女"
colnames(population2)[7] <- "日本人人口"
colnames(population2)[8] <- "日本人人口.男"
colnames(population2)[9] <- "日本人人口.女"
head(population2)
```


## 数字のカンマをなくす
カンマ,を何もないように置換(sub)する
```{r}
population2$"年齢" <- as.numeric(sub(",","",(population2$"年齢"))) 
population2$"総人口" <- as.numeric(sub(",","",(population2$"総人口")))
population2$"総人口.男" <- as.numeric(sub(",","",(population2$"総人口.男")))
population2$"総人口.女" <- as.numeric(sub(",","",(population2$"総人口.女")))
population2$"日本人人口" <- as.numeric(sub(",","",(population2$"日本人人口")))
population2$"日本人人口.男" <- as.numeric(sub(",","",(population2$"日本人人口.男")))
population2$"日本人人口.女" <- as.numeric(sub(",","",(population2$"日本人人口.女")))

head(population2)
summary(population2)
```



## ggplotに適したデータに変換

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
data1 <- data.frame(c(population2[1],population2[3],population2[4],population2[5]))
#データをlong化
#keyのところが日本語にすると不具合（適当な英語を当てはめる）
data1 <- data1 %>%
  tidyr::gather(key ="set", 
                value ="人口","総人口", "総人口.男","総人口.女")
head(data1)

#gatherで変換した要素をファクター化
data1$"set"<- factor(data1$"set")
summary(data1)
```



## ggplotによるグラフ化

```{r ggplot}
library(ggplot2)
windowsFonts(mincho=windowsFont("MS Mincho")) ## 「MS 明朝」を登録
g1 <- ggplot(data1,aes(x=data1$"年齢",y=data1$"人口",colour=data1$"set"))
g1+geom_line(size=1)+
  labs(title ="日本の総人口(2019年10月)" )+
  labs(colour="分類")+
  xlab("年齢(歳）")+
  ylab("人数(千人）")+
  scale_x_continuous(breaks=seq(0,100,10))+
  theme_bw(base_size = 16,base_family = "mincho")
```

## 男女別　総人口と日本人人口
データ作成とプロット準備
```{r data2}
data2 <- data.frame(c(population2[1],
                      population2[4],
                      population2[5],
                      population2[8],
                      population2[9]))

data2 <- data2 %>%
  tidyr::gather(key ="set", 
                value ="人口",
                "総人口.男", "総人口.女","日本人人口.男","日本人人口.女")
head(data2);tail(data2)
#gatherで変換した要素をファクター化
data2$"set"<- factor(data2$"set")
summary(data2)

data3 <- data2 %>% filter(set == "総人口.男" | set =="日本人人口.男") 
head(data3);tail(data3)

g2 <- ggplot(data3,aes(x=data3$"年齢",y=data3$"人口",colour=data3$"set"))
g2 <- g2+geom_line(size=1)+
  
  labs(title ="人口 男(2019年10月)" )+
  labs(colour="分類")+
  xlab("年齢(歳）")+
  ylab("人数(千人）")+
  scale_x_continuous(breaks=seq(0,100,10))+
  scale_y_continuous(breaks=seq(0,1000,250),limits=c(0,1250))+
  theme(text = element_text(family = "mincho"),
        legend.position = c(0,0),legend.justification = c(0,0))

data4 <- data2 %>% filter(set == "総人口.女" | set =="日本人人口.女")
head(data4);tail(data4)

g3 <- ggplot(data4,aes(x=data4$"年齢",y=data4$"人口",colour=data4$"set"))
g3 <- g3+geom_line(size=1)+
  labs(title ="人口　女(2019年10月)" )+
  labs(colour="分類")+
  xlab("年齢(歳）")+
  ylab("人数(千人）")+
  scale_x_continuous(breaks=seq(0,100,10))+
  scale_y_continuous(breaks=seq(0,1000,250),limits=c(0,1250))+
  theme(text = element_text(family = "mincho"),
        legend.position = c(0,0),legend.justification = c(0,0))
```


  
## 並べてプロット
```{r plot2}
library(cowplot)
plot_grid(g2,g3,ncol=2,nrow=1)

```




